### ISSUE TITLE
Exporting Error

### ISSUE THREAD

**Issue by filibis** [0xafbf/blender-datasmith-export#1]
Hi @0xafbf ,
I'm getting below error when I tried to export .udatasmith. My blender version: 2.80 (sub 74), branch: master, commit date: 2019-06-19 18:29, hash: `rBd30f72dfd8ac`

Test .blend file: [udatasmith_test.zip](https://github.com/0xafbf/blender-datasmith-export/files/3316961/udatasmith_test.zip)

```
location: <unknown location>:-1

location: <unknown location>:-1
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.version

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:74
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.use_selection

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:75
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.global_scale

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:76
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.include_metadata

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:77
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.embed_textures

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:78
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.batch_mode

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:79
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.version

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:74
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.use_selection

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:75
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.global_scale

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:76
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.include_metadata

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:77
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.embed_textures

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:78
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.batch_mode

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:79
Traceback (most recent call last):
  File "C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py", line 85, in execute
    return export_datasmith.save(self, context, **keywords)
  File "C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\export_datasmith.py", line 328, in save
    scene = collect_to_uscene(bpy.context)
  File "C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\export_datasmith.py", line 319, in collect_to_uscene
    uobj = collect_object(obj, uscene, context=context)
  File "C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\export_datasmith.py", line 256, in collect_object
    uobj.focus_distance = bl_cam.dof_distance
AttributeError: 'Camera' object has no attribute 'dof_distance'

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by 0xafbf** [comment]
Hello Emir, Thanks for trying out the datasmith plugin.

Probably you downloaded the plugin from the releases page, please download the latest code from the Project homepage https://github.com/0xafbf/blender-datasmith-export from the green download button, select download zip. This way you will have the latest code. 

From: Emir Sinan Gürlek
Sent: Saturday, June 22, 2019 10:04 AM
To: 0xafbf/blender-datasmith-export
Cc: Andrés Botero; Mention
Subject: [0xafbf/blender-datasmith-export] Exporting Error (#1)

Hi @0xafbf ,
I'm getting below error when I tried to export .udatasmith. My blender version: 2.80 (sub 74), branch: master, commit date: 2019-06-19 18:29, hash: rBd30f72dfd8ac
Test .blend file: udatasmith_test.zip
location: <unknown location>:-1

location: <unknown location>:-1
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.version

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:74
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.use_selection

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:75
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.global_scale

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:76
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.include_metadata

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:77
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.embed_textures

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:78
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.batch_mode

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:79
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.version

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:74
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.use_selection

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:75
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.global_scale

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:76
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.include_metadata

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:77
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.embed_textures

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:78
rna_uiItemR: property not found: EXPORT_SCENE_OT_datasmith.batch_mode

C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py:79
Traceback (most recent call last):
  File "C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\__init__.py", line 85, in execute
    return export_datasmith.save(self, context, **keywords)
  File "C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\export_datasmith.py", line 328, in save
    scene = collect_to_uscene(bpy.context)
  File "C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\export_datasmith.py", line 319, in collect_to_uscene
    uobj = collect_object(obj, uscene, context=context)
  File "C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_udatasmith\export_datasmith.py", line 256, in collect_object
    uobj.focus_distance = bl_cam.dof_distance
AttributeError: 'Camera' object has no attribute 'dof_distance'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by filibis** [comment]
Thanks for replying back. I downloaded the master as you described and it's working great.
The reason I downloaded from release page before is because in the README.md files you redirect users there. You may want to change that (:

By the way I suggest you to create a topic in [Blenderartist forum](https://blenderartists.org/). I'm sure lots of people will be interested in this. Also consider selling the addon in [Blendermarket](https://www.blendermarket.com) and/or [Gumroad](https://gumroad.com/) as a support option.

**Comment by 0xafbf** [comment]
Thank you @filibis . Right now I have just worked on getting the code working, but those are definitely some places that I plan to publish the addon. I consider this resolved so I will close this issue now.
Please feel free to continue the discussion in discord.

**Comment by 0xafbf** [comment]
Thank you @filibis . Right now I have just worked on getting the code working, but those are definitely some places that I plan to publish the addon. I consider this resolved so I will close this issue now.
Please feel free to continue the discussion in discord.

**Comment by MarKosk0** [comment]
I am downloading it from the latest version from the master with my blender 3.4, and it gives me the same error...
