### ISSUE TITLE
Hidden objects get exported

### ISSUE THREAD

**Issue by eobet** [0xafbf/blender-datasmith-export#15]
There should be a checkbox on export for "export hidden objects" and perhaps also "selected objects only".

**Comment by eobet** [comment]
Note, I actually hid the collection, and not the individual objects, so that should be something to check for (either that, or just only export the current selection, because I believe that's how the Max plugin behaves).

**Comment by RogueSheep-nl** [comment]
A 'selected-objects-only' option would be very handy indeed.

**Comment by 0xafbf** [comment]
I added an option to export selected objects only.
the datasmith format allows to send visibility state in the scene, I would need to check that later
