### ISSUE TITLE
Why i can't find the export option UI

### ISSUE THREAD

**Issue by byoxy1980** [0xafbf/blender-datasmith-export#17]
When I selected the model export in blender, I didn't see the options UI in the demo video

**Comment by 0xafbf** [comment]
There were a lot of placeholder options that didn't do anything and I removed them in recent versions.
I recently updated the project with useful options, please check them out and let me know what you think =D

**Comment by byoxy1980** [comment]
ok i will thx




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Andrés Botero"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月29日(星期天) 凌晨4:40
收件人:&nbsp;"0xafbf/blender-datasmith-export"<blender-datasmith-export@noreply.github.com&gt;;
抄送:&nbsp;"Eason"<664029750@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [0xafbf/blender-datasmith-export] Why i can't find the export option UI (#17)




There were a lot of placeholder options that didn't do anything and I removed them in recent versions.
 I recently updated the project with useful options, please check them out and let me know what you think =D
