### ISSUE TITLE
Archipack Boolean

### ISSUE THREAD

**Issue by zyadmardini** [0xafbf/blender-datasmith-export#19]
Hello , I am having a problem with applying the boolean modifiers of the archipack geometry when exporting to datasmith. If i export the scene as FBX, all booleans from windows and doors get applied properly. Does the datasmith export plugin apply all modifiers before exporting?

**Comment by 0xafbf** [comment]
I recently added an export option to apply modifiers on export. Please download and let me know how it works.
If you use discord, we can discuss it directly there (check the readme for the link).

**Comment by 0xafbf** [comment]
Didn't receive any response, and my guess is that this case is now handled correctly, so I'm closing this issue.
