### ISSUE TITLE
It's absolutely necessary to use your custom UE4 build?

### ISSUE THREAD

**Issue by juangea** [0xafbf/blender-datasmith-export#25]
Hi there, I have not tried it yet, but I would like to know if it's absolutely necessary to use your custom UE4 build? or can we use it in a normal release build from UE4, even if it has some caveats :)

**Comment by 0xafbf** [comment]
The custom build is not necessary, but it will help for better import of
some features of the datasmith format.
If you want to match what my custom build does, you will need to:

* select normal map textures and enable the "flip green channel" option in
them
* select the mask textures (roughness, etc...), uncheck the "sRGB" flag and
revert the "gamma curve" to 1.0
* make sure that point light and area light attenuation radius are correct
(currently, UE4 only reads attenuation radius for spot lights

as you can see, these are not a big deal, but help in making a seamless
experience.
The greatest annoyance is when you import textures and materials, if the
texture is marked as sRGB, the texture samplers are created as "Color", so
when you turn sRGB off, the materials break as you need to switch the
samplers to "Linear Color". This doesn't happen if the textures are
imported as non-sRGB from the start.

Please let me know if you have any questions, you can also ask questions in
Discord.

**Comment by 0xafbf** [comment]
Just to add, in UE4 4.25, the sRGB flag is no longer an issue.
The other problems still exist, I will start pushing more to get these merged for the next UE4 version.
